ALTER TABLE `pla_off` CHANGE `OFF_MOUNT` `OFF_MONTH` INT(2) NOT NULL;
ALTER TABLE `pla_off` ADD `OFF_YEAR` VARCHAR(4) NULL AFTER `OFF_MONTH`;
INSERT INTO `pla_off` (`OFF_ID`, `OFF_NAME`, `OFF_DAY`, `OFF_MONTH`, `OFF_YEAR`, `OFF_ID_REP`) VALUES (NULL, "Jour de l'an", '01', '01', NULL, '1'), (NULL, "Paques", '21', '04', '2019', '0');

ALTER TABLE `pla_off` CHANGE `OFF_ID_REP` `OFF_REPEAT` INT(32) NOT NULL;
ALTER TABLE `pla_off` CHANGE `OFF_DAY` `OFF_DAY` VARCHAR(2) NOT NULL;
ALTER TABLE `pla_off` CHANGE `OFF_MONTH` `OFF_MONTH` VARCHAR(2) NOT NULL;