ALTER TABLE `yda_users` ADD `USR_THEME` BOOLEAN NOT NULL DEFAULT TRUE COMMENT '0 : dark, 1 : light' AFTER `USR_TEAMVIEWER`, 
ADD `USR_SIDEBAR` BOOLEAN NOT NULL DEFAULT TRUE COMMENT '0 : close, 1 : open' AFTER `USR_THEME`;
