CREATE TABLE `yoda`.`CFG_PREFERENCES` ( `CPR_ID` INT(32) NOT NULL AUTO_INCREMENT , `CPR_ID_USR` INT(32) NOT NULL , `CPR_SIDEBAR` BOOLEAN NOT NULL COMMENT '0 : open, 1 : closed' , `CPR_THEME` BOOLEAN NOT NULL COMMENT '0 : dark , 1 : light' , `CPR_COLOR_PLANNING` BOOLEAN NOT NULL COMMENT '0 : slot, 1 : tech' , `CPR_CODE_PLANNING` BOOLEAN NOT NULL COMMENT '0 : code, 1 : name' , PRIMARY KEY (`CPR_ID`)) ENGINE = MyISAM;

ALTER TABLE `CFG_PREFERENCES` CHANGE `CPR_SIDEBAR` `CPR_SIDEBAR` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '0 : open, 1 : closed';
ALTER TABLE `CFG_PREFERENCES` CHANGE `CPR_THEME` `CPR_THEME` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '0 : dark , 1 : light';
ALTER TABLE `CFG_PREFERENCES` CHANGE `CPR_COLOR_PLANNING` `CPR_COLOR_PLANNING` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '0 : slot, 1 : tech';
ALTER TABLE `CFG_PREFERENCES` CHANGE `CPR_CODE_PLANNING` `CPR_CODE_PLANNING` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '0 : code, 1 : name';
ALTER TABLE `CFG_PREFERENCES` ADD UNIQUE(`CPR_ID_USR`);

ALTER TABLE `yda_users` DROP `USR_SIDEBAR`;
ALTER TABLE `yda_users` DROP `USR_THEME`;

ALTER TABLE `cfg_preferences` CHANGE `CPR_CODE_PLANNING` `CPR_LABEL_PLANNING` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '0 : code, 1 : name';